services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_movie_api_development
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "rails_movie_api_development"]
      interval: 5s
      timeout: 3s
      retries: 5
 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["./docker-entrypoint-dev.sh"]
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/rails_movie_api_development
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["./docker-entrypoint-dev.sh"]
    command: ["bundle", "exec", "rspec"]
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgres://postgres:password@db:5432/rails_movie_api_test
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

volumes:
  postgres_data:
  bundle_cache:
