---
openapi: 3.0.1
info:
  title: Movie API
  version: v1
  description: A REST API for managing movies and watchlists with JWT authentication
paths:
  "/api/v1/movies":
    get:
      summary: list movies
      tags:
      - Movies
      description: Retrieve all movies
      parameters:
      - name: page
        in: query
        description: 'Page number (default: 1)'
        required: false
        example: 1
        schema:
          type: integer
      - name: per_page
        in: query
        description: 'Items per page (default: 2, max: 100)'
        required: false
        example: 2
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: The Matrix
                        description:
                          type: string
                          example: A computer hacker...
                        release_year:
                          type: integer
                          example: 1999
                        created_at:
                          type: string
                          format: datetime
                        updated_at:
                          type: string
                          format: datetime
                      required:
                      - id
                      - title
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      total_pages:
                        type: integer
                        example: 3
                      total_count:
                        type: integer
                        example: 50
                      per_page:
                        type: integer
                        example: 10
                    required:
                    - current_page
                    - total_pages
                    - total_count
                    - per_page
                required:
                - data
                - meta
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                    description: HTTP status code
                  error:
                    type: string
                    example: Internal Server Error
                    description: Error message
                required:
                - status
                - error
servers:
- url: http://localhost:3000
  description: Development server
