---
openapi: 3.0.1
info:
  title: Movie API
  version: v1
  description: A REST API for managing movies and watchlists with JWT authentication
paths:
  "/api/v1/movies":
    get:
      summary: List movies
      tags:
      - Movies
      description: Retrieve all movies
      parameters:
      - "$ref": "#/components/parameters/page"
      - "$ref": "#/components/parameters/per_page"
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                data:
                - id: 1
                  title: Movie 1
                  description: A great movie about something interesting.
                  release_year: 2001
                  created_at: '2025-08-12T02:53:29.829Z'
                  updated_at: '2025-08-12T02:53:29.829Z'
                - id: 2
                  title: Movie 2
                  description: A great movie about something interesting.
                  release_year: 2002
                  created_at: '2025-08-12T02:53:29.833Z'
                  updated_at: '2025-08-12T02:53:29.833Z'
                meta:
                  current_page: 1
                  total_pages: 3
                  total_count: 5
                  per_page: 2
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/movie"
                  meta:
                    "$ref": "#/components/schemas/pagination_metadata"
                required:
                - data
                - meta
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                    description: HTTP status code
                  error:
                    type: string
                    example: Internal Server Error
                    description: Error message
                required:
                - status
                - error
    post:
      summary: Create a movie
      tags:
      - Movies
      description: Create a new movie
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              example:
                data:
                  id: 6
                  title: Movie 6
                  description: A great movie about something interesting.
                  release_year: 2006
                  created_at: '2025-08-12T02:53:29.867Z'
                  updated_at: '2025-08-12T02:53:29.867Z'
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/movie"
                required:
                - data
        '422':
          description: Invalid request
          content:
            application/json:
              example:
                errors:
                - Title can't be blank
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                      example: Title can't be blank
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                movie:
                  type: object
                  properties:
                    title:
                      type: string
                      example: The Matrix
                    description:
                      type: string
                      nullable: true
                      example: A computer hacker learns from mysterious rebels about
                        the true nature of his reality.
                    release_year:
                      type: integer
                      nullable: true
                      example: 1999
                  required:
                  - title
              required:
              - movie
        required: true
  "/api/v1/movies/{id}":
    get:
      summary: Get movie by ID
      tags:
      - Movies
      description: Retrieve a specific movie by ID
      parameters:
      - name: id
        in: path
        description: Movie ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Movie found
          content:
            application/json:
              example:
                data:
                  id: 7
                  title: Movie 7
                  description: A great movie about something interesting.
                  release_year: 2007
                  created_at: '2025-08-12T02:53:29.871Z'
                  updated_at: '2025-08-12T02:53:29.871Z'
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/movie"
        '404':
          description: Movie not found
          content:
            application/json:
              example:
                error:
                  message: Movie not found
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Movie not found
                    required:
                    - message
                required:
                - error
    delete:
      summary: Delete movie by ID
      tags:
      - Movies
      description: Delete a specific movie by ID
      parameters:
      - name: id
        in: path
        description: Movie ID
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Movie deleted successfully
        '404':
          description: Movie not found
          content:
            application/json:
              example:
                error:
                  message: Movie not found
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Movie not found
                    required:
                    - message
                required:
                - error
servers:
- url: http://localhost:3000
  description: Development server
components:
  schemas:
    movie:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: The Matrix
        description:
          type: string
          nullable: true
          example: A computer hacker learns about....
        release_year:
          type: integer
          nullable: true
          example: 1999
        created_at:
          type: string
          format: date-time
          example: '2023-01-01T00:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2023-01-02T00:00:00Z'
      required:
      - id
      - title
      - created_at
      - updated_at
    pagination_metadata:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        total_pages:
          type: integer
          example: 3
        total_count:
          type: integer
          example: 50
        per_page:
          type: integer
          example: 10
      required:
      - current_page
      - total_pages
      - total_count
      - per_page
  parameters:
    page:
      name: page
      in: query
      schema:
        type: integer
      description: 'Page number (default: 1)'
      required: false
      example: 1
    per_page:
      name: per_page
      in: query
      schema:
        type: integer
      description: 'Items per page (default: 2, max: 100)'
      required: false
      example: 2
